
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author enriquejosegaleanotalavera
 */
public class Principal extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public Principal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Diagramas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Diagramas_Flujo_ventana = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Fuente = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        Estilo_de_fuente = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        Tamano = new javax.swing.JComboBox();
        Panel_De_Diagramas = new javax.swing.JPanel();
        UML = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        DIagramas_UML_ventana = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        Opciones = new javax.swing.JPopupMenu();
        Cambiar = new javax.swing.JMenuItem();
        Diagrama_de_FLujo = new javax.swing.JLabel();
        Cambios_de_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Diagrama de Flujo Basico");

        jLabel2.setText("Permite crear diagramas de flujo, descendentes de");

        jLabel3.setText("seguimiento de informacion, planeamineto de");

        jLabel4.setText("procesos y de prediccion de estructuras. Contiene");

        jLabel5.setText("conectores y vinculos");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/220px-DiagramaFlujoLampara.svg.png"))); // NOI18N

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DiagramasLayout = new javax.swing.GroupLayout(Diagramas);
        Diagramas.setLayout(DiagramasLayout);
        DiagramasLayout.setHorizontalGroup(
            DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(55, 55, 55))))
        );
        DiagramasLayout.setVerticalGroup(
            DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagramasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(195, 195, 195))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel18.setText("Formas para diagramas de flujo");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datos.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/documentos.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/if.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/in_fin.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Proceso.png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/separadorV.png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subpro.png"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel7.setText("Fuente: ");

        jLabel16.setText("Estilo de Fuente: ");

        jLabel17.setText("Tamaño: ");

        Panel_De_Diagramas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_De_Diagramas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Panel_De_Diagramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_De_DiagramasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_De_DiagramasLayout = new javax.swing.GroupLayout(Panel_De_Diagramas);
        Panel_De_Diagramas.setLayout(Panel_De_DiagramasLayout);
        Panel_De_DiagramasLayout.setHorizontalGroup(
            Panel_De_DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Panel_De_DiagramasLayout.setVerticalGroup(
            Panel_De_DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Diagramas_Flujo_ventanaLayout = new javax.swing.GroupLayout(Diagramas_Flujo_ventana.getContentPane());
        Diagramas_Flujo_ventana.getContentPane().setLayout(Diagramas_Flujo_ventanaLayout);
        Diagramas_Flujo_ventanaLayout.setHorizontalGroup(
            Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                        .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(Fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estilo_de_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(71, 71, 71)
                        .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(342, Short.MAX_VALUE))
                    .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                        .addComponent(Panel_De_Diagramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))))
        );
        Diagramas_Flujo_ventanaLayout.setVerticalGroup(
            Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                        .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estilo_de_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Panel_De_Diagramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("UML");

        jLabel10.setText("Es un Lenguaje grafico para visualizar,");

        jLabel11.setText("especificar, construir y documentar un sistema");

        jLabel12.setText("UML ofrece un estandar para describir un \"Plano\"");

        jLabel13.setText("del sistema.");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/ejemplo.jpg"))); // NOI18N

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UMLLayout = new javax.swing.GroupLayout(UML);
        UML.setLayout(UMLLayout);
        UMLLayout.setHorizontalGroup(
            UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UMLLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        UMLLayout.setVerticalGroup(
            UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UMLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel14.setText("Prueba");

        javax.swing.GroupLayout DIagramas_UML_ventanaLayout = new javax.swing.GroupLayout(DIagramas_UML_ventana.getContentPane());
        DIagramas_UML_ventana.getContentPane().setLayout(DIagramas_UML_ventanaLayout);
        DIagramas_UML_ventanaLayout.setHorizontalGroup(
            DIagramas_UML_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DIagramas_UML_ventanaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel14)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        DIagramas_UML_ventanaLayout.setVerticalGroup(
            DIagramas_UML_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DIagramas_UML_ventanaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel14)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jButton11.setText("jButton11");

        Cambiar.setText("Cambiar");
        Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarActionPerformed(evt);
            }
        });
        Opciones.add(Cambiar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Diagrama_de_FLujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/220px-DiagramaFlujoLampara.svg.png"))); // NOI18N
        Diagrama_de_FLujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Diagrama_de_FLujoMouseClicked(evt);
            }
        });

        Cambios_de_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout Cambios_de_panelLayout = new javax.swing.GroupLayout(Cambios_de_panel);
        Cambios_de_panel.setLayout(Cambios_de_panelLayout);
        Cambios_de_panelLayout.setHorizontalGroup(
            Cambios_de_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        Cambios_de_panelLayout.setVerticalGroup(
            Cambios_de_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Diagrama de Flujo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/ejemplo.jpg"))); // NOI18N

        jButton3.setText("Diagrama UML");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Diagrama_de_FLujo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(Cambios_de_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Diagrama_de_FLujo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Cambios_de_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Diagrama_de_FLujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Diagrama_de_FLujoMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_Diagrama_de_FLujoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
		// TODO add your handling code here:
		cambios = false;
		if (cambios == false) {

			Diagramas.setLocation(5, 5);
			Diagramas.setSize(500, 580);
			Cambios_de_panel.add(Diagramas, BorderLayout.CENTER);
			Cambios_de_panel.revalidate();
			//Cambios_de_panel.repaint();

		}

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
		// TODO add your handling code here:
		Diagramas_Flujo_ventana.setModal(true);
		Diagramas_Flujo_ventana.pack();
		Diagramas_Flujo_ventana.setLocationRelativeTo(this);
		Diagramas_Flujo_ventana.setVisible(true);
		//
		//publicacion_texto.setModal(true);
		//publicacion_texto.pack();
		//publicacion_texto.setLocationRelativeTo(this);
		//publicacion_texto.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
		// TODO add your handling code here:
		DIagramas_UML_ventana.setModal(true);
		DIagramas_UML_ventana.pack();
		DIagramas_UML_ventana.setLocationRelativeTo(this);
		DIagramas_UML_ventana.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
		// TODO add your handling code here:
		cambios = true;
		if (cambios == true) {
//			Cambios_de_panel.repaint();

			UML.setLocation(5, 5);
			UML.setSize(500, 580);
			Cambios_de_panel.add(UML, BorderLayout.CENTER);
			Cambios_de_panel.revalidate();
			//Cambios_de_panel.repaint();

		}
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.GREEN);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("Procesos");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/datos.png"));

		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 645) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("Documentos");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/documentos.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}
			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				/* if (evt.isMetaDown()) {
				 System.out.println(global);
				 pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
				 }*/
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.ORANGE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("if");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/if.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.CYAN);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);

		datos.setText("Inicio o Finalizacion");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/in_fin.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("Proceso");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/Proceso.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});

    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);

		Panel_De_Diagramas.add(datos);
		datos.setText("Separador");
		datos.setSize(45, 80);
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/separador.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});


    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("Separador Vertical");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/separadorV.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("Subproceso");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/subpro.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton13MouseClicked

    private void Panel_De_DiagramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_De_DiagramasMouseClicked
		// TODO add your handling code here:
		if (evt.isMetaDown()) {
			//if (global.getX() && global.getY()) {
			Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
			//}
		}
    }//GEN-LAST:event_Panel_De_DiagramasMouseClicked

    private void CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarActionPerformed
        // TODO add your handling code here:
		String cambio = JOptionPane.showInputDialog(Diagramas_Flujo_ventana,"Ingrese el nombre de la variable");
		global.setText(cambio);
    }//GEN-LAST:event_CambiarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Principal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cambiar;
    private javax.swing.JPanel Cambios_de_panel;
    private javax.swing.JDialog DIagramas_UML_ventana;
    private javax.swing.JLabel Diagrama_de_FLujo;
    private javax.swing.JPanel Diagramas;
    private javax.swing.JDialog Diagramas_Flujo_ventana;
    private javax.swing.JComboBox Estilo_de_fuente;
    private javax.swing.JComboBox Fuente;
    private javax.swing.JPopupMenu Opciones;
    private javax.swing.JPanel Panel_De_Diagramas;
    private javax.swing.JComboBox Tamano;
    private javax.swing.JPanel UML;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
boolean cambios;
	JLabel global = null;
}
