
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author enriquejosegaleanotalavera
 */
public class Principal extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public Principal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Diagramas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Diagramas_Flujo_ventana = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        Panel_De_Diagramas = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        UML = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        DIagramas_UML_ventana = new javax.swing.JDialog();
        PanelUML = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Opciones = new javax.swing.JPopupMenu();
        dar_nombre_a_variables = new javax.swing.JMenuItem();
        verArchivo = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_1 = new javax.swing.JTextArea();
        OpcionesUML = new javax.swing.JPopupMenu();
        dar_Nombre_a_Clase = new javax.swing.JMenuItem();
        dar_atributos_a_la_clase = new javax.swing.JMenuItem();
        Nombre = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        ta_nombre_Clase = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jr_Scanner = new javax.swing.JRadioButton();
        jr_ArrayList = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        librerias = new javax.swing.ButtonGroup();
        Atributos = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton16 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Diagrama_de_FLujo = new javax.swing.JLabel();
        Cambios_de_panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Diagrama de Flujo Basico");

        jLabel2.setText("Permite crear diagramas de flujo, descendentes de");

        jLabel3.setText("seguimiento de informacion, planeamineto de");

        jLabel4.setText("procesos y de prediccion de estructuras. Contiene");

        jLabel5.setText("conectores y vinculos");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/220px-DiagramaFlujoLampara.svg.png"))); // NOI18N

        jButton2.setText("Crear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DiagramasLayout = new javax.swing.GroupLayout(Diagramas);
        Diagramas.setLayout(DiagramasLayout);
        DiagramasLayout.setHorizontalGroup(
            DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(55, 55, 55))))
        );
        DiagramasLayout.setVerticalGroup(
            DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiagramasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiagramasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagramasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(195, 195, 195))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel18.setText("Formas para diagramas de flujo");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/datos.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/documentos.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/if.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/in_fin.png"))); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Proceso.png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/separador.png"))); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/separadorV.png"))); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subpro.png"))); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        Panel_De_Diagramas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_De_Diagramas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Panel_De_Diagramas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_De_DiagramasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_De_DiagramasLayout = new javax.swing.GroupLayout(Panel_De_Diagramas);
        Panel_De_Diagramas.setLayout(Panel_De_DiagramasLayout);
        Panel_De_DiagramasLayout.setHorizontalGroup(
            Panel_De_DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        Panel_De_DiagramasLayout.setVerticalGroup(
            Panel_De_DiagramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        jButton17.setText("Ver que hay en el arrayList");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jMenu2.setText("Opciones");

        jMenuItem3.setText("Crear directorio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.META_MASK));
        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.META_MASK));
        jMenuItem2.setText("Guardar Como");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Abrir Archivo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        Diagramas_Flujo_ventana.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout Diagramas_Flujo_ventanaLayout = new javax.swing.GroupLayout(Diagramas_Flujo_ventana.getContentPane());
        Diagramas_Flujo_ventana.getContentPane().setLayout(Diagramas_Flujo_ventanaLayout);
        Diagramas_Flujo_ventanaLayout.setHorizontalGroup(
            Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Panel_De_Diagramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jButton17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Diagramas_Flujo_ventanaLayout.setVerticalGroup(
            Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Diagramas_Flujo_ventanaLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(Diagramas_Flujo_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Panel_De_Diagramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addGap(15, 15, 15))
        );

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("UML");

        jLabel10.setText("Es un Lenguaje grafico para visualizar,");

        jLabel11.setText("especificar, construir y documentar un sistema");

        jLabel12.setText("UML ofrece un estandar para describir un \"Plano\"");

        jLabel13.setText("del sistema.");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/ejemplo.jpg"))); // NOI18N

        jButton4.setText("Crear");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UMLLayout = new javax.swing.GroupLayout(UML);
        UML.setLayout(UMLLayout);
        UMLLayout.setHorizontalGroup(
            UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UMLLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        UMLLayout.setVerticalGroup(
            UMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UMLLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelUML.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout PanelUMLLayout = new javax.swing.GroupLayout(PanelUML);
        PanelUML.setLayout(PanelUMLLayout);
        PanelUMLLayout.setHorizontalGroup(
            PanelUMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        PanelUMLLayout.setVerticalGroup(
            PanelUMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton14.setText("Clase");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DIagramas_UML_ventanaLayout = new javax.swing.GroupLayout(DIagramas_UML_ventana.getContentPane());
        DIagramas_UML_ventana.getContentPane().setLayout(DIagramas_UML_ventanaLayout);
        DIagramas_UML_ventanaLayout.setHorizontalGroup(
            DIagramas_UML_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DIagramas_UML_ventanaLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelUML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DIagramas_UML_ventanaLayout.setVerticalGroup(
            DIagramas_UML_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton11.setText("jButton11");

        dar_nombre_a_variables.setText("Dar nombre a las variables");
        dar_nombre_a_variables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dar_nombre_a_variablesActionPerformed(evt);
            }
        });
        Opciones.add(dar_nombre_a_variables);

        jLabel7.setText("Lo que contiene el archivo");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        ta_1.setColumns(20);
        ta_1.setRows(5);
        jScrollPane1.setViewportView(ta_1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout verArchivoLayout = new javax.swing.GroupLayout(verArchivo.getContentPane());
        verArchivo.getContentPane().setLayout(verArchivoLayout);
        verArchivoLayout.setHorizontalGroup(
            verArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verArchivoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(verArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        verArchivoLayout.setVerticalGroup(
            verArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verArchivoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        dar_Nombre_a_Clase.setText("Nombre Clase y Librerias");
        dar_Nombre_a_Clase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dar_Nombre_a_ClaseMouseClicked(evt);
            }
        });
        dar_Nombre_a_Clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dar_Nombre_a_ClaseActionPerformed(evt);
            }
        });
        OpcionesUML.add(dar_Nombre_a_Clase);

        dar_atributos_a_la_clase.setText("Atributos");
        dar_atributos_a_la_clase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dar_atributos_a_la_claseActionPerformed(evt);
            }
        });
        OpcionesUML.add(dar_atributos_a_la_clase);

        jLabel14.setText("Nombre");

        jLabel17.setText("Librerias");

        librerias.add(jr_Scanner);
        jr_Scanner.setText("Scanner");

        librerias.add(jr_ArrayList);
        jr_ArrayList.setText("ArrayList");

        jButton15.setText("Dar nombre");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NombreLayout = new javax.swing.GroupLayout(Nombre.getContentPane());
        Nombre.getContentPane().setLayout(NombreLayout);
        NombreLayout.setHorizontalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel14)
                        .addGap(30, 30, 30)
                        .addComponent(ta_nombre_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel17)
                        .addGap(36, 36, 36)
                        .addComponent(jr_Scanner))
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel19)
                        .addGap(66, 66, 66)
                        .addComponent(jr_ArrayList))
                    .addGroup(NombreLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton15)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        NombreLayout.setVerticalGroup(
            NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NombreLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ta_nombre_Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jr_Scanner))
                .addGap(17, 17, 17)
                .addGroup(NombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jr_ArrayList))
                .addGap(47, 47, 47)
                .addComponent(jButton15)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel16.setText("jLabel16");

        jLabel20.setText("Nombre");

        jCheckBox1.setText("Public");

        jCheckBox2.setText("Private ");

        jCheckBox3.setText("Protected");

        jCheckBox4.setText("Package");

        jLabel21.setText("Tipo");

        jLabel22.setText("Compuesta");

        jRadioButton3.setText("ArrayList");

        jButton16.setText("Dar atributos");

        javax.swing.GroupLayout AtributosLayout = new javax.swing.GroupLayout(Atributos.getContentPane());
        Atributos.getContentPane().setLayout(AtributosLayout);
        AtributosLayout.setHorizontalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel21))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jCheckBox1)
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBox3))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox4))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel22)
                        .addGap(25, 25, 25)
                        .addComponent(jRadioButton3))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel20)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        AtributosLayout.setVerticalGroup(
            AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AtributosLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4))
                .addGap(28, 28, 28)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel22))
                    .addComponent(jRadioButton3))
                .addGap(24, 24, 24)
                .addGroup(AtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AtributosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Diagrama_de_FLujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/220px-DiagramaFlujoLampara.svg.png"))); // NOI18N
        Diagrama_de_FLujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Diagrama_de_FLujoMouseClicked(evt);
            }
        });

        Cambios_de_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout Cambios_de_panelLayout = new javax.swing.GroupLayout(Cambios_de_panel);
        Cambios_de_panel.setLayout(Cambios_de_panelLayout);
        Cambios_de_panelLayout.setHorizontalGroup(
            Cambios_de_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        Cambios_de_panelLayout.setVerticalGroup(
            Cambios_de_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Diagrama de Flujo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/ejemplo.jpg"))); // NOI18N

        jButton3.setText("Diagrama UML");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Diagrama_de_FLujo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(Cambios_de_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Diagrama_de_FLujo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Cambios_de_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Diagrama_de_FLujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Diagrama_de_FLujoMouseClicked
		// TODO add your handling code here:
    }//GEN-LAST:event_Diagrama_de_FLujoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
		// TODO add your handling code here:
		cambios = false;
		if (cambios == false) {

			Diagramas.setLocation(5, 5);
			Diagramas.setSize(500, 580);
			Cambios_de_panel.add(Diagramas, BorderLayout.CENTER);
			Cambios_de_panel.revalidate();
			//Cambios_de_panel.repaint();

		}

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
		// TODO add your handling code here:
		Diagramas_Flujo_ventana.setModal(true);
		Diagramas_Flujo_ventana.pack();
		Diagramas_Flujo_ventana.setLocationRelativeTo(this);
		Diagramas_Flujo_ventana.setVisible(true);
		//
		//publicacion_texto.setModal(true);
		//publicacion_texto.pack();
		//publicacion_texto.setLocationRelativeTo(this);
		//publicacion_texto.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
		// TODO add your handling code here:
		DIagramas_UML_ventana.setModal(true);
		DIagramas_UML_ventana.pack();
		DIagramas_UML_ventana.setLocationRelativeTo(this);
		DIagramas_UML_ventana.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
		// TODO add your handling code here:
		cambios = true;
		if (cambios == true) {
//			Cambios_de_panel.repaint();

			UML.setLocation(5, 5);
			UML.setSize(500, 580);
			Cambios_de_panel.add(UML, BorderLayout.CENTER);
			Cambios_de_panel.revalidate();
			//Cambios_de_panel.repaint();

		}
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
		// TODO add your handling code here:
		//Boton de datos
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.GREEN);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("datos");
		arregloLabel.add(datos);
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/datos.png"));

		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 645) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
		// TODO add your handling code her
		//Boton de documentos
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.WHITE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("documentos");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/documentos.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}
			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				/* if (evt.isMetaDown()) {
				 System.out.println(global);
				 pp_OP.show(evt.getComponent(), evt.getX(), evt.getY());
				 }*/
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.ORANGE);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);
		datos.setText("if");
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/if.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
		// TODO add your handling code here:
		final JLabel datos = new JLabel();
		datos.setOpaque(true);
		datos.setBackground(Color.CYAN);
		datos.setSize(100, 70);
		Panel_De_Diagramas.add(datos);

		Inicio_o_Fin++;
		if (Inicio_o_Fin == 1) {
			datos.setText("Inicio");
			arregloLabel.add(0, datos);
		} else {

			datos.setText("Fin");
			arregloLabel.add(datos);
		}
		datos.setHorizontalTextPosition(SwingConstants.CENTER);
		datos.setLocation(100, 100);
		datos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/in_fin.png"));
		datos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos;
				if ((datos.getLocation().x + evt.getX() - datos.getWidth() / 2) >= 0
						&& (datos.getLocation().x + evt.getX() - datos.getWidth() / 2) <= 800) {
					datos.setLocation(datos.getLocation().x + evt.getX() - datos.getWidth() / 2,
							datos.getLocation().y + evt.getY() - datos.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos;
			}
		});

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
		// TODO add your handling code here:
		//boton de procesos
		final JLabel DatosProcesos = new JLabel();
		DatosProcesos.setOpaque(true);
		DatosProcesos.setBackground(Color.WHITE);
		DatosProcesos.setSize(100, 70);
		Panel_De_Diagramas.add(DatosProcesos);
		DatosProcesos.setText("proceso");
		arregloLabel.add(DatosProcesos);
		DatosProcesos.setHorizontalTextPosition(SwingConstants.CENTER);
		DatosProcesos.setLocation(100, 100);
		DatosProcesos.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/Proceso.png"));
		DatosProcesos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = DatosProcesos;
				if ((DatosProcesos.getLocation().x + evt.getX() - DatosProcesos.getWidth() / 2) >= 0
						&& (DatosProcesos.getLocation().x + evt.getX() - DatosProcesos.getWidth() / 2) <= 800) {
					DatosProcesos.setLocation(DatosProcesos.getLocation().x + evt.getX() - DatosProcesos.getWidth() / 2,
							DatosProcesos.getLocation().y + evt.getY() - DatosProcesos.getHeight() / 2);

				}

			}
		});
		DatosProcesos.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = DatosProcesos;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = DatosProcesos;
			}

			public void mouseExited(MouseEvent arg0) {
				global = DatosProcesos;
			}

			public void mousePressed(MouseEvent arg0) {
				global = DatosProcesos;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = DatosProcesos;
			}
		});

    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
		// TODO add your handling code here:
		//separadores de los if cuando es si o no
		final JLabel datos3 = new JLabel();
		datos3.setOpaque(true);
		datos3.setBackground(Color.WHITE);
		Panel_De_Diagramas.add(datos3);
		datos3.setSize(45, 80);
		datos3.setHorizontalTextPosition(SwingConstants.CENTER);
		datos3.setLocation(100, 100);
		datos3.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/separador.png"));
		datos3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos3;
				if ((datos3.getLocation().x + evt.getX() - datos3.getWidth() / 2) >= 0
						&& (datos3.getLocation().x + evt.getX() - datos3.getWidth() / 2) <= 800) {
					datos3.setLocation(datos3.getLocation().x + evt.getX() - datos3.getWidth() / 2,
							datos3.getLocation().y + evt.getY() - datos3.getHeight() / 2);

				}

			}
		});
		datos3.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos3;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos3;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos3;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos3;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos3;
			}
		});


    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
		// TODO add your handling code here:
		//separadores de los if cuando es si o no
		final JLabel datos4 = new JLabel();
		datos4.setOpaque(true);
		datos4.setBackground(Color.WHITE);
		datos4.setSize(100, 70);
		Panel_De_Diagramas.add(datos4);
		datos4.setHorizontalTextPosition(SwingConstants.CENTER);
		datos4.setLocation(100, 100);
		datos4.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/separadorV.png"));
		datos4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos4;
				if ((datos4.getLocation().x + evt.getX() - datos4.getWidth() / 2) >= 0
						&& (datos4.getLocation().x + evt.getX() - datos4.getWidth() / 2) <= 800) {
					datos4.setLocation(datos4.getLocation().x + evt.getX() - datos4.getWidth() / 2,
							datos4.getLocation().y + evt.getY() - datos4.getHeight() / 2);

				}

			}
		});
		datos4.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos4;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos4;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos4;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos4;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos4;
			}
		});
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
		// TODO add your handling code here:
		final JLabel datos5 = new JLabel();
		datos5.setOpaque(true);
		datos5.setBackground(Color.WHITE);
		datos5.setSize(100, 70);
		Panel_De_Diagramas.add(datos5);
		datos5.setText("subproceso");
		//arregloLabel.add(datos);
		datos5.setHorizontalTextPosition(SwingConstants.CENTER);
		datos5.setLocation(100, 100);
		datos5.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/subpro.png"));
		datos5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				global = datos5;
				if ((datos5.getLocation().x + evt.getX() - datos5.getWidth() / 2) >= 0
						&& (datos5.getLocation().x + evt.getX() - datos5.getWidth() / 2) <= 800) {
					datos5.setLocation(datos5.getLocation().x + evt.getX() - datos5.getWidth() / 2,
							datos5.getLocation().y + evt.getY() - datos5.getHeight() / 2);

				}

			}
		});  //agrega los label
		datos5.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				global = datos5;
				if (evt.isMetaDown()) {
					System.out.println(global);
					Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				global = datos5;
			}

			public void mouseExited(MouseEvent arg0) {
				global = datos5;
			}

			public void mousePressed(MouseEvent arg0) {
				global = datos5;
			}

			public void mouseReleased(MouseEvent arg0) {
				global = datos5;
			}
		});
    }//GEN-LAST:event_jButton13MouseClicked

    private void Panel_De_DiagramasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_De_DiagramasMouseClicked
		// TODO add your handling code here:
		if (evt.isMetaDown()) {
			//if (global.getX() && global.getY()) {
			Opciones.show(evt.getComponent(), evt.getX(), evt.getY());
			//}
		}
    }//GEN-LAST:event_Panel_De_DiagramasMouseClicked

    private void dar_nombre_a_variablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dar_nombre_a_variablesActionPerformed
		// TODO add your handling code here:
		String cambio = JOptionPane.showInputDialog(Diagramas_Flujo_ventana, "Ingrese el nombre de la variable");
		global.setText(cambio);
    }//GEN-LAST:event_dar_nombre_a_variablesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
		File archivo = new File("./archivo.txt");
		FileWriter fw = null;
		BufferedWriter bw = null;
		for (JLabel label : arregloLabel) {
			if (label.getText().equals("Inicio")) {
				try {
					fw = new FileWriter(archivo, false);
					bw = new BufferedWriter(fw);
					bw.write("#include <iostream>");
					bw.write("\n");
					bw.write("using namespace std;");
					bw.write("\n");
					bw.write("int main(){");

					bw.write("\n");
					bw.flush();

				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			if (label.getText().equals("proceso") && ((label.getText().equals("+")) || (label.getText().equals("-")) || (label.getText().equals("/")) || (label.getText().equals("*")))) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" " + label.getText());
					bw.write(";");
					bw.write("\n");
					bw.flush();

				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			if (label.getText().contains("proceso") && !label.getText().contains("\"") && label.getText().contains("imprimir")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" " + "cout<<" + label.getText().replace("imprimir", "") + "<<endl");
					bw.write(";");
					bw.write("\n");
					bw.flush();

				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			if (label.getText().contains("proceso") && label.getText().contains("imprimir") && label.getText().contains("\"")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" cout<<" + label.getText().replace("imprimir", ""));
					bw.write(";");
					bw.write("\n");
					bw.flush();

				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}

			}
			if (label.getText().contains("proceso") && label.getText().contains("entero")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" int" + label.getText().replace("entero", ""));
					bw.write(";");
					bw.write("\n");
					bw.flush();
				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}

			}
			if (label.getText().equals("proceso") && label.getText().contains("real")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" double" + label.getText().replace("real", ""));
					bw.write(";");
					bw.write("\n");
					bw.flush();

				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}
			}

			if (label.getText().contains("datos")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" cin>>" + label.getText() + ";");
					bw.write("\n");
					bw.flush();
				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}

			}
			if (label.getText().equals("Fin")) {
				try {
					fw = new FileWriter(archivo, true);
					bw = new BufferedWriter(fw);
					bw.write(" system(\"pause\")");
					bw.write(";");
					bw.write("\n");
					bw.write(" return 0");
					bw.write(";");
					bw.write("\n");
					bw.write("}");
					bw.flush();
				} catch (IOException ex) {
					Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
			try {
				bw.close();
				fw.close();
			} catch (IOException ex) {
				Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		JOptionPane.showMessageDialog(Diagramas_Flujo_ventana, "Se genero el codigo correctamente");
		
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
		// TODO add your handling code here:
		JFileChooser filechoose = new JFileChooser();
		int seleccion = filechoose.showSaveDialog(Diagramas_Flujo_ventana);
		if (seleccion == JFileChooser.APPROVE_OPTION) {
			File dir = filechoose.getSelectedFile();
			boolean fueCreado = dir.mkdir();
			if (fueCreado) {
				JOptionPane.showMessageDialog(Diagramas_Flujo_ventana, "Directorio Creado con exito");
			} else {
				JOptionPane.showMessageDialog(Diagramas_Flujo_ventana, "El directorio no se creo con exito");
			}
		}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		// TODO add your handling code here:

		File fichero = null;
		FileReader fr = null;
		BufferedReader br = null;
		ta_1.setText(" ");
		try {
			JFileChooser jfc = new JFileChooser();
			FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de Texto", "txt");
			FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Imagenes", "jpg", "png", "bmp");
			jfc.setFileFilter(filtro);
			jfc.addChoosableFileFilter(filtro2);
			int seleccion = jfc.showOpenDialog(verArchivo);
			if (seleccion == JFileChooser.APPROVE_OPTION) {
				fichero = jfc.getSelectedFile();
				fr = new FileReader(fichero);
				br = new BufferedReader(fr);
				String linea;
				ta_1.setText(" ");
				while ((linea = br.readLine()) != null) {
					ta_1.append(linea);
					ta_1.append("\n");
				}
			}
		} catch (Exception e) {
		}
		try {
			br.close();
			fr.close();
		} catch (Exception e) {
		}
		verArchivo.setModal(true);
		verArchivo.pack();
		verArchivo.setLocationRelativeTo(this);
		verArchivo.setVisible(true);
//		Diagramas_Flujo_ventana.setModal(true);
//		Diagramas_Flujo_ventana.pack();
//		Diagramas_Flujo_ventana.setLocationRelativeTo(this);
//		Diagramas_Flujo_ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
		// TODO add your handling code here:
		final JLabel datosUML = new JLabel();
		datosUML.setOpaque(true);
		datosUML.setBackground(Color.WHITE);
		datosUML.setSize(100, 70);
		PanelUML.add(datosUML);

		//arregloLabel.add(datos);
		datosUML.setHorizontalTextPosition(SwingConstants.CENTER);
		datosUML.setLocation(100, 100);
		//datosUML.setIcon(new ImageIcon("/Users/enriquejosegaleanotalavera/Desktop/IProyecto/subpro.png"));
		datosUML.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseDragged(java.awt.event.MouseEvent evt) {
				seleccionado = datosUML;
				if ((datosUML.getLocation().x + evt.getX() - datosUML.getWidth() / 2) >= 0
						&& (datosUML.getLocation().x + evt.getX() - datosUML.getWidth() / 2) <= 800) {
					datosUML.setLocation(datosUML.getLocation().x + evt.getX() - datosUML.getWidth() / 2,
							datosUML.getLocation().y + evt.getY() - datosUML.getHeight() / 2);

				}

			}
		});  //agrega los label
		datosUML.addMouseListener(new MouseListener() {
			public void mouseClicked(MouseEvent evt) {
				seleccionado = datosUML;
				if (evt.isMetaDown()) {
					System.out.println(seleccionado);
					OpcionesUML.show(evt.getComponent(), evt.getX(), evt.getY());
				}
			}

			public void mouseEntered(MouseEvent arg0) {
				seleccionado = datosUML;
			}

			public void mouseExited(MouseEvent arg0) {
				seleccionado = datosUML;
			}

			public void mousePressed(MouseEvent arg0) {
				seleccionado = datosUML;
			}

			public void mouseReleased(MouseEvent arg0) {
				seleccionado = datosUML;
			}
		});
    }//GEN-LAST:event_jButton14MouseClicked

    private void dar_Nombre_a_ClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dar_Nombre_a_ClaseMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_dar_Nombre_a_ClaseMouseClicked

    private void dar_Nombre_a_ClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dar_Nombre_a_ClaseActionPerformed
		Nombre.setModal(true);
		Nombre.pack();
		Nombre.setVisible(true);
		Nombre.setLocationRelativeTo(Nombre);
    }//GEN-LAST:event_dar_Nombre_a_ClaseActionPerformed

    private void dar_atributos_a_la_claseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dar_atributos_a_la_claseActionPerformed
		// TODO add your handling code here:
		Atributos.setModal(true);
		Atributos.pack();
		Atributos.setVisible(true);
		Atributos.setLocationRelativeTo(Nombre);
    }//GEN-LAST:event_dar_atributos_a_la_claseActionPerformed

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
		// TODO add your handling code here:
		String nombre;
		String RadioScanner;
		String RadioArrayList;

		nombre = ta_nombre_Clase.getText();
		if (jr_Scanner.isSelected()) {
			RadioScanner = "Scanner";
		} else if (jr_ArrayList.isSelected()) {
			RadioArrayList = "ArrayList";
		}
		seleccionado.setText(nombre);

		seleccionado.setHorizontalTextPosition(SwingConstants.CENTER);
		JOptionPane.showMessageDialog(Nombre, "Se le dio el nombre correctamente");

    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
		// TODO add your handling code here:
		for (JLabel t : arregloLabel) {
			System.out.println(t.getName());
		}
    }//GEN-LAST:event_jButton17MouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Principal.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Principal.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Principal.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Principal.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Principal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Atributos;
    private javax.swing.JPanel Cambios_de_panel;
    private javax.swing.JDialog DIagramas_UML_ventana;
    private javax.swing.JLabel Diagrama_de_FLujo;
    private javax.swing.JPanel Diagramas;
    private javax.swing.JDialog Diagramas_Flujo_ventana;
    private javax.swing.JDialog Nombre;
    private javax.swing.JPopupMenu Opciones;
    private javax.swing.JPopupMenu OpcionesUML;
    private javax.swing.JPanel PanelUML;
    private javax.swing.JPanel Panel_De_Diagramas;
    private javax.swing.JPanel UML;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem dar_Nombre_a_Clase;
    private javax.swing.JMenuItem dar_atributos_a_la_clase;
    private javax.swing.JMenuItem dar_nombre_a_variables;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton jr_ArrayList;
    private javax.swing.JRadioButton jr_Scanner;
    private javax.swing.ButtonGroup librerias;
    private javax.swing.JTextArea ta_1;
    private javax.swing.JTextField ta_nombre_Clase;
    private javax.swing.JDialog verArchivo;
    // End of variables declaration//GEN-END:variables
	boolean cambios;
	JLabel global = null;

	ArrayList<JLabel> arregloLabel = new ArrayList();
	int Inicio_o_Fin = 0;
	JLabel seleccionado;
}
